# Generated by Django 3.0.6 on 2020-06-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('date_of_birth', models.CharField(max_length=11, verbose_name='Дата рождения')),
                ('the_class', models.CharField(max_length=2, verbose_name='Класс')),
                ('educational_institution', models.CharField(max_length=50, verbose_name='Учеб.учреждение')),
                ('place_of_study', models.CharField(max_length=15, verbose_name='Место обучения')),
                ('country', models.CharField(max_length=10, verbose_name='Страна')),
                ('region', models.CharField(max_length=10, verbose_name='Регион')),
                ('e_mail', models.CharField(max_length=20, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Телефон')),
                ('events', models.CharField(max_length=200, verbose_name='Мероприятия')),
            ],
        ),
    ]
