# Generated by Django 3.0.6 on 2020-06-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='records',
            options={'verbose_name': 'запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterField(
            model_name='records',
            name='date_of_birth',
            field=models.CharField(max_length=10, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='records',
            name='region',
            field=models.CharField(max_length=17, verbose_name='Регион'),
        ),
    ]
